overrides:
  - files:
      - "**/*.{js,mjs,cjs,jsx}"
    options:
      plugins:
        - "@prettier/plugin-oxc"
      parser: oxc
  - files:
      - "**/*.{ts,mts,cts,tsx}"
    options:
      plugins:
        - "@prettier/plugin-oxc"
      parser: oxc-ts