#!/bin/sh

if [ -n "$2" ]; then
  PREV_HEAD="$1"
  NEW_HEAD="$2"
else
  PREV_HEAD="HEAD@{1}"
  NEW_HEAD="HEAD"
fi

if git diff --name-only "$PREV_HEAD" "$NEW_HEAD" | grep -q "package-lock.json"; then
  echo "Husky: Lock file changed. Running 'npm ci'..."
  npm ci
fi
